# Generated by Django 4.2.2 on 2023-07-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userspage", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=200, null=True),
        ),
    ]
