# Generated by Django 4.2.2 on 2024-01-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userspage", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("Cash on Delivery", "Cash on Delivery")], max_length=200
            ),
        ),
    ]
