# Generated by Django 4.2.2 on 2024-01-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userspage", "0011_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_no",
            field=models.CharField(max_length=10),
        ),
    ]
