# Generated by Django 4.2.2 on 2024-01-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userspage", "0012_alter_order_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact_no",
            field=models.CharField(max_length=15),
        ),
    ]
