# Generated by Django 4.2.2 on 2024-01-12 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="register",
        ),
    ]
