# Generated by Django 4.2.2 on 2023-07-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0002_category_rename_food_proce_food_food_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="demo_app.category",
            ),
        ),
    ]
