# Generated by Django 4.2.2 on 2023-07-14 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0004_remove_food_image_url_food_food_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="stock",
        ),
    ]
