# Generated by Django 4.2.2 on 2023-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0005_remove_food_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="created_at",
            field=models.CharField(max_length=50),
        ),
    ]
