# Generated by Django 4.2.2 on 2024-01-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0007_rename_created_at_food_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_price",
            field=models.PositiveIntegerField(),
        ),
    ]
